vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe
volume=80
volume-max=100
osd-bar=no
osd-font-size=32
sub-auto=fuzzy
sub-font-size=36
autofit-larger=90%x90%
keep-open=yes
screenshot-dir=~/Pictures/Screenshots
screenshot-format=png
