# Hyprland master config — sources all modules

################
### PROGRAMS ###
################

$terminal = kitty
$browser = flatpak run io.gitlab.librewolf-community

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybindings.conf


#################
### AUTOSTART ###
#################

exec-once = uwsm app -- wl-clip-persist --clipboard regular
exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- hyprsunset
exec-once = uwsm app -- nilpower --daemon
exec-once = uwsm app -- nilwall
