# Hyprland master config — sources all modules

################
### PROGRAMS ###
################

$terminal = kitty
$browser = zen-browser

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybindings.conf


#################
### AUTOSTART ###
#################

exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- nilpower --daemon
exec-once = uwsm app -- nilwall
